### ISSUE TITLE
Renameodk : add possibility to specify the divider

### ISSUE THREAD

**Issue by TristanFR** [rapidsurveys/odkr#47]
Hi Ernest,

just writing here our discussion about the possibility to adjust the parameters of the function renameodk.
I am using it the simple way : renameodk(Table) ; perhaps I could specify which characters  should be understood as the end of the prefix ?

In details:
ODK adds "-" between groups of questions. So it gives something like **PREFIX-Variable_name** in my database.
Currently, the function is able to clean the prefix with "."
I changed my code to add a "." at the end of the prefix, so now I have **PREFIX.-Variable_name**, which gives **-Variable_name** as an output of the renameodk function.

I cannot add the "." at the beginning of the variable names (refused by ODK).
So I would like to specify in the function's argument that the prefix ends by ".-"

Would it be feasible ?

Thanks for your support,
Tristan

**Comment by ernestguevarra** [comment]
Hi Tristan,

Thanks for posting this here. This is very helpful. I will work on a fix for what you need. now and will push it into GitHub.

Best,
Ernest

**Comment by ernestguevarra** [comment]
Hi Tristan,

Please install the updated version of `odkr` via GitHub.

And then, in R, type the following command to see how to use the updated renameODK function:

`?odkr::renameODK`

This function can now rename the ODK dataset with a specified separator hence you can now use "-"

**Comment by TristanFR** [comment]
Perfect ! very convenient, thanks a lot
